//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Suedi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.Selecciona = new HashSet<Selecciona>();
        }
    
        public string E_MAIL_A { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Contraseña { get; set; }
        public System.DateTime Fecha_Nac { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Selecciona> Selecciona { get; set; }
    }
}
