//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Suedi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Selecciona
    {
        public int ID_Selecciona { get; set; }
        public string E_Mail_A { get; set; }
        public string E_Mail_P { get; set; }
        public int ID_Curso { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
